import type {IChatCacheState} from '@/src/reducers/cache/chatCache';
import type {IPhotosCacheState} from '@/src/reducers/cache/photosCache';
import type {IPicturesCacheState} from '@/src/reducers/cache/picturesCache';
import type {IVaultCacheState} from '@/src/reducers/cache/vaultCache';
import type {IConnectionRequestsState} from '@/src/reducers/connections/connectionRequests';
import type {IConnectionsState} from '@/src/reducers/connections/connections';
import type {ISentConnectionRequestsState} from '@/src/reducers/connections/sentConnectionRequests';
import type {IGroupRequestsState} from '@/src/reducers/groups/groupRequests';
import type {IGroupsState} from '@/src/reducers/groups/groups';
import type {IMembersState} from '@/src/reducers/groups/members';
import type {IFinishedTransactionsState} from '@/src/reducers/iap/finishedTransactions';
import type {IChatNotificationsIdState} from '@/src/reducers/notificationsId/chatNotificationsId';
import type {IGroupsNotificationsIdState} from '@/src/reducers/notificationsId/groupsNotificationsId';
import type {IActiveRoomsState} from '@/src/reducers/stick-room/activeRooms';
import type {IAlbumImagesIdsState} from '@/src/reducers/stick-room/albumImagesIds';
import type {IChatActionsState} from '@/src/reducers/stick-room/chatActions';
import type {IChatAlbumsState} from '@/src/reducers/stick-room/chatAlbums';
import type {IChatAudioState} from '@/src/reducers/stick-room/chatAudio';
import type {IChatFilesState} from '@/src/reducers/stick-room/chatFiles';
import type {IChatsStoragesState} from '@/src/reducers/stick-room/chatsStorages';
import type {ILastSeenState} from '@/src/reducers/stick-room/lastSeen';
import type {IMessagesState} from '@/src/reducers/stick-room/messages';
import type {IMutingUsersState} from '@/src/reducers/stick-room/mutingUsers';
import type {IRemovedRoomsState} from '@/src/reducers/stick-room/removedRooms';
import type {IRoomFilesState} from '@/src/reducers/stick-room/roomFiles';
import type {IFilesState} from '@/src/reducers/vault/files';
import type {IFilesTreeState} from '@/src/reducers/vault/filesTree';
import type {IPhotosState} from '@/src/reducers/vault/photos';
import type {IVaultAlbumsState} from '@/src/reducers/vault/vaultAlbums';
import type {IVaultNotesState} from '@/src/reducers/vault/vaultNotes';
import type {IAppState} from '@/src/reducers/app';
import type {IAuthState} from '@/src/reducers/auth';
import type {IAppTempState} from '@/src/reducers/appTemp';
import type {IBlockedState} from '@/src/reducers/blocked';
import type {ICameraUploadsSettingsState} from '@/src/reducers/cameraUploadsSettings';
import type {ICreatingState} from '@/src/reducers/creating';
import type {IDownloadState} from '@/src/reducers/download';
import type {IErrorsState} from '@/src/reducers/errors';
import type {IFetchedState} from '@/src/reducers/fetched';
import type {IModalState} from '@/src/reducers/modal';
import type {IMutualConnectionsState} from '@/src/reducers/mutualConnections';
import type {IMutualGroupsState} from '@/src/reducers/mutualGroups';
import type {IPendingSessionsState} from '@/src/reducers/pendingSessions';
import type {IProgressState} from '@/src/reducers/progress';
import type {IRefreshEntitiesState} from '@/src/reducers/refreshEntities';
import type {SelectedImagesState} from '@/src/reducers/selectedImages';
import type {IUploadState} from '@/src/reducers/upload';
import type {IUrlState} from '@/src/reducers/url';
import type {IUsersState} from '@/src/reducers/users';
import type {IViewableItemState} from '@/src/reducers/viewableItem';
import type {IViewableVideoState} from '@/src/reducers/viewableVideo';
import type {TSubscription} from '@/src/types/IAP';
import {OrientationState} from '@/src/reducers/orientation';
import {AppActiveState} from '@/src/reducers/appState';
import {TKeyBoardHeight} from '@/src/reducers/keyboardHeight';

export interface IApplicationState {
    app: IAppState;
    auth: IAuthState;
    appTemp: IAppTempState;
    blocked: IBlockedState;
    cameraUploadsSettings: ICameraUploadsSettingsState;
    creating: ICreatingState;
    download: IDownloadState;
    errors: IErrorsState;
    fetched: IFetchedState;
    modal: IModalState;
    mutualConnections: IMutualConnectionsState;
    mutualGroups: IMutualGroupsState;
    pendingSessions: IPendingSessionsState;
    progress: IProgressState;
    refreshEntities: IRefreshEntitiesState;
    selectedImages: SelectedImagesState;
    upload: IUploadState;
    url: IUrlState;
    users: IUsersState;
    viewableItem: IViewableItemState;
    viewableVideo: IViewableVideoState;
    chatCache: IChatCacheState;
    photosCache: IPhotosCacheState;
    picturesCache: IPicturesCacheState;
    vaultCache: IVaultCacheState;
    connectionRequests: IConnectionRequestsState;
    connections: IConnectionsState;
    sentConnectionRequests: ISentConnectionRequestsState;
    groupRequests: IGroupRequestsState;
    groups: IGroupsState;
    members: IMembersState;
    finishedTransactions: IFinishedTransactionsState;
    chatNotificationsId: IChatNotificationsIdState;
    groupsNotificationsId: IGroupsNotificationsIdState;
    activeRooms: IActiveRoomsState;
    albumImagesIds: IAlbumImagesIdsState;
    chatActions: IChatActionsState;
    chatAlbums: IChatAlbumsState;
    chatAudio: IChatAudioState;
    chatFiles: IChatFilesState;
    chatsStorages: IChatsStoragesState;
    lastSeen: ILastSeenState;
    messages: IMessagesState;
    mutingUsers: IMutingUsersState;
    removedRooms: IRemovedRoomsState;
    roomFiles: IRoomFilesState;
    files: IFilesState;
    filesTree: IFilesTreeState;
    photos: IPhotosState;
    vaultAlbums: IVaultAlbumsState;
    vaultNotes: IVaultNotesState;
    subs: TSubscription[];
    orientation: OrientationState;
    appState: AppActiveState;
    keyboardHeight: TKeyBoardHeight;
}
