require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
use_frameworks! :linkage => :static

# Convert all permission pods into static libraries
pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}

  installer.pod_targets.each do |pod|
    if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-') || pod.name.eql?('YapDatabase')
      def pod.build_type;
         Pod::BuildType.static_library # >= 1.9
      end
    end
  end
end

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
$FirebaseSDKVersion = '10.4.0'

platform :ios, '15.0'
prepare_react_native_project!

#flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled
#
#linkage = ENV['USE_FRAMEWORKS']
#if linkage != nil
#  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#  use_frameworks! :linkage => linkage.to_sym
#end
pod 'GoogleUtilities', :modular_headers => true
pod 'SimpleKeychain', '1.1.0'
pod 'SwiftyJSON'
# pod 'StickProtocolLib', '1.2.5' `currently using it locally due to some issues with Xcode 14.3 compiling the library`
pod 'StickySignalProtocolC', '1.0.2'
pod 'SignalArgon2'
pod 'CryptoSwift'
pod 'SQLCipher', ">= 4.0.1", :modular_headers => true
pod 'YapDatabase/SQLCipher', :git => 'https://github.com/signalapp/YapDatabase.git', branch: 'signal-release', :modular_headers => true
pod 'Mantle', :modular_headers => true
pod 'GRKOpenSSLFramework', git: 'https://github.com/signalapp/GRKOpenSSLFramework', branch: 'mkirk/1.0.2t'
pod 'CocoaLumberjack'
pod 'Alamofire'

target 'Sticknet' do
  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  permissions_path = '../node_modules/react-native-permissions/ios'
    pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
    pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
    pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
    pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
    pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"


  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
#    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'ShareExtension'

  target 'NotificationServiceExtension'


  target 'SticknetTests' do
    inherit! :complete
    # Pods for testing
  end
  
  extension_targets = ['NotificationServiceExtension', 'ShareExtension']

  post_install do |installer|
    
    # if which bitcode_strip >/dev/null; then
    #   echo "🔨 Stripping bitcode from embedded frameworks"
    #   for BIN in "$TARGET_BUILD_DIR/$FRAMEWORKS_FOLDER_PATH"/*.framework/* ; do
    #     bitcode_strip "$BIN" -r -o "$BIN" 2>/dev/null || true
    #   done
    # fi
    
#    bitcode_strip_path = `xcrun --find bitcode_strip`.chop!
#     def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
#       framework_path = File.join(Dir.pwd, framework_relative_path)
#       command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
#       puts "Stripping bitcode: #{command}"
#       system(command)
#     end
#
#     framework_paths = [
#       "Pods/LogRocket/LogRocket.xcframework/ios-arm64/LogRocket.framework/LogRocket",
#       "Pods/hermes-engine/destroot/Library/Frameworks/macosx/hermes.framework/hermes",
#       "Pods/hermes-engine/destroot/Library/Frameworks/macosx/hermes.framework/Versions/Current/hermes",
#       "Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64/hermes.framework/hermes",
#       "Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64_x86_64-maccatalyst/hermes.framework/hermes",
#       
#       "Pods/GRKOpenSSLFramework/GRKOpenSSLFramework.xcframework/ios-arm64/GRKOpenSSLFramework.framework/openssl",
#       "Pods/GRKOpenSSLFramework/GRKOpenSSLFramework.framework/openssl",
#       
#       "Pods/GRKOpenSSLFramework/GRKOpenSSLFramework.xcframework/ios-arm64/openssl.framework/openssl",
#       "Pods/GRKOpenSSLFramework/openssl.framework/openssl",
#       
#       "Pods/GRKOpenSSLFramework/openssl.xcframework/ios-arm64/openssl.framework/openssl",
#       "Pods/GRKOpenSSLFramework/openssl.framework/openssl",
#       
#       
#       "Pods/StickySignalProtocolC/StickySignalProtocolC.xcframework/ios-arm64/StickySignalProtocolC.framework/StickySignalProtocolC",
#       "Pods/StickySignalProtocolC/StickySignalProtocolC.framework/StickySignalProtocolC"
#     ]
#
#     framework_paths.each do |framework_relative_path|
#       strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
#     end
    
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
      installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      if target.name == 'Sentry'
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'YES'
      else
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
  end
  end
end
