import {cameraPermission, micPermission, photosPermission} from './permissions';
import {
    nEveryRow,
    arrayUnique,
    hashCode,
    getParameterByName,
    formatTime,
    saveToGallery,
    parseNumber,
    monthNames,
    timeSince,
    parseBirthDay,
    getGalleryAlbums,
    getUniqueDeviceId,
    getTabName,
    requestAppReview,
    getDeviceName,
    createBlobsIds,
    createCategoriesBlobsIds,
    createFavoritesIds,
    saveToGalleryMultiple,
    getAppSettings,
    formDataToObject,
    createFileSections,
    createFilesList,
    dispatchAlbums,
    prepareFiles,
    getNewPostsNetwork,
    isCloseToBottom,
    exportFile,
    validateEmail,
    formatBytes,
    nav,
    n,
    findKeyByValue,
    getAllNestedKeys,
    lightenRGBColor,
    createActiveChatsList,
    createChatsStoragesList,
    getUnreadCount,
    shortenAddress,
} from './common';
import {statusBarHeight, isIphoneXD} from './notch';
import {formatMessageDate, formatAMPM, isSingleEmoji} from './chatUtils';
import {saveTestingPhotos} from './e2e';
import {getStatusBarHeight} from './StatusBar';

export {
    cameraPermission,
    micPermission,
    photosPermission,
    nEveryRow,
    arrayUnique,
    statusBarHeight,
    hashCode,
    getParameterByName,
    formatTime,
    saveToGallery,
    parseNumber,
    monthNames,
    timeSince,
    parseBirthDay,
    getGalleryAlbums,
    formatMessageDate,
    getUniqueDeviceId,
    getTabName,
    requestAppReview,
    getDeviceName,
    createBlobsIds,
    createCategoriesBlobsIds,
    createFavoritesIds,
    saveToGalleryMultiple,
    getAppSettings,
    formDataToObject,
    saveTestingPhotos,
    formatAMPM,
    isIphoneXD,
    createFilesList,
    createFileSections,
    dispatchAlbums,
    getStatusBarHeight,
    prepareFiles,
    getNewPostsNetwork,
    isCloseToBottom,
    exportFile,
    validateEmail,
    formatBytes,
    isSingleEmoji,
    nav,
    n,
    findKeyByValue,
    getAllNestedKeys,
    lightenRGBColor,
    createActiveChatsList,
    createChatsStoragesList,
    getUnreadCount,
    shortenAddress,
};
